CFLAGS += -I $(BASE)/components/common/thirdparty/openamp/include

obj-$(CONFIG_COMPONENTS_SCHEDULER_JITTER_TEST) += scheduler_jitter.o
obj-$(CONFIG_COMPONENTS_INTERRUPT_JITTER_TEST) += interrupt_jitter.o
obj-$(CONFIG_COMPONENTS_OPENAMP_JITTER_TEST) += openamp_jitter.o