/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#include "platform_sun8iw20.h"

const char *irq_major_string[PLIC_IRQ_NUM] = {
	[0 ... 15] = NULL,
	[16] = "CPUX_MSGBOX_R",
	[17] = NULL,
	[18] = "UART0",
	[19] = "UART1",
	[20] = "UART2",
	[21] = "UART3",
	[22] = "UART4",
	[23] = "UART5",
	[24] = NULL,
	[25] = "TWI0",
	[26] = "TWI1",
	[27] = "TWI2",
	[28] = "TWI3",
	[29 ... 30] = NULL,
	[31] = "SPI0",
	[32] = "SPI1",
	[33] = NULL,
	[34] = "PWM",
	[35] = "IR_TX",
	[36] = "LEDC",
	[37] = "CAN0",
	[38] = "CAN1",
	[39] = "SPDIF",
	[40] = "MDIC",
	[41] = "AUDIO_CODEC",
	[42] = "I2S_PCM0",
	[43] = "I2S_PCM1",
	[44] = "I2S_PCM2",
	[45] = "USB0_DEVICE",
	[46] = "USB0_EHCI",
	[47] = "USB0_OHCI",
	[48] = NULL,
	[49] = "USB1_EHCI",
	[51] = "USB1_OHCI",
	[51 ... 55] = NULL,
	[56] = "SD0",
	[57] = "SD1",
	[58] = "SD2",
	[59] = "MSI",
	[60] = "SMC",
	[61] = NULL,
	[62] = "GMAC",
	[63] = "TZMA_ERR",
	[64] = "CCU_FREE",
	[65] = "AHB_HREADY_TIME_OUT",
	[66] = "DMA_NS",
	[67] = "DMA_S",
	[68] = "CE_NS",
	[69] = "CE_S",
	[70] = "SPINLOCK",
	[71] = "HSTIMER0",
	[72] = "HSTIMER1",
	[73] = "GPA",
	[74] = "THS",
	[75] = "TIMER0",
	[76] = "TIMER1",
	[77] = "LR",
	[78] = "TPA",
	[79] = "WATCHDOG",
	[80] = "IOMMU",
	[81] = NULL,
	[82] = "VE",
	[83 ... 84] = NULL,
	[85] = "GPIOB_NS",
	[86] = "GPIOB_S",
	[87] = "GPIOC_NS",
	[88] = "GPIOC_S",
	[89] = "GPIOD_NS",
	[90] = "GPIOD_S",
	[91] = "GPIOE_NS",
	[92] = "GPIOE_S",
	[93] = "GPIOF_NS",
	[94] = "GPIOF_S",
	[95] = "GPIOG_NS",
	[96] = "GPIOG_S",
	[97 ... 100] = NULL,
	[101] = "CPUX_MSGBOX_DSP_W",
	[102] = "CPUX_MSGBOX_RISCV_W",
	[103] = "DE",
	[104] = "DI",
	[105] = "G2D",
	[106] = "LCD",
	[107] = "TV",
	[108] = "DSI",
	[109] = "HDMI",
	[110] = "TVE",
	[111] = "CSI_DMA0",
	[112] = "CSI_DMA1",
	[113 ... 115] = NULL,
	[116] = "CSI_PARSER0",
	[117 ... 121] = NULL,
	[122] = "CSI_TOP_PKT",
	[123] = "TVD",
	[124 ... 135] = NULL,
	[136] = "DSP_DEE",
	[137] = "DSP_PFE",
	[138] = "DSP_WDG",
	[139] = "DSP_MBOX_CPUX_W",
	[140] = "DSP_MBOX_RISCV_W",
	[141] = "DSP_TZMA",
	[142] = "DMAC_IRQ_DSP_NS",
	[143] = "DMAC_IRQ_DSP_S",
	[144] = "RISCV_MBOX_RISCV",
	[145] = "RISCV_MBOX_DSP",
	[146] = "RISCV_MBOX_CPUX",
	[147] = "RISCV_WDG",
	[148 ... 151]	= NULL,
/* CPUS */
	[152] = "NMI",
	[153] = "PPU",
	[154] = "TWD",
	[155] = NULL,
	[156] = "R_TIMER0",
	[157] = "R_TIMER1",
	[158] = "R_TIMER2",
	[159] = "R_TIMER3",
	[160] = "LARM0",
	[161 ... 166] = NULL,
	[167] = "IRRX",
	[168 ... 169] = NULL,
	[170] = "AHBS_HREADY_TIME_OUT",
	[171 ... 175] = NULL,
/* CPUX */
	[176] = "C0_CTI0",
	[177] = "C0_CTI1",
	[178 ... 179] = NULL,
	[180] = "CO_COMMTX0",
	[181] = "C0_COMMTX1",
	[182 ... 187] = NULL,
	[188] = "C0_PMU0",
	[189] = "C0_PMU1",
	[190 ... 191] = NULL,
	[192] = "C0_AXI_ERROR",
	[193] = NULL,
	[194] = "AXI_WR_IRQ",
	[195] = "AXI_RD_IRQ",
	[196] = "DEGPWRUPREQ_OUT0",
	[197] = "DEGPWRUPREQ_OUT1",
};


