/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 frank@allwinnertech.com
 */

#ifndef _CCU_SUN55IW3_MCU_H_
#define _CCU_SUN55IW3_MCU_H_

#define SUNXI_MCU_CCU_BASE      0x7102000

enum {
	CLK_PLL_MCU_AUDIO1 = 0,
	CLK_PLL_MCU_AUDIO1_DIV2,
	CLK_PLL_MCU_AUDIO1_DIV5,
	CLK_PLL_MCU_AUDIO_OUT,
	CLK_DSP_DSP,
	CLK_MCU_I2S0,
	CLK_MCU_I2S1,
	CLK_MCU_I2S2,
	CLK_MCU_I2S3,
	CLK_MCU_I2S3_ASRC,
	CLK_BUS_MCU_I2S0,
	CLK_BUS_MCU_I2S1,
	CLK_BUS_MCU_I2S2,
	CLK_BUS_MCU_I2S3,
	CLK_MCU_SPDIF_TX,
	CLK_MCU_SPDIF_RX,
	CLK_BUS_MCU_SPDIF,
	CLK_MCU_DMIC,
	CLK_BUS_MCU_DMIC,
	CLK_MCU_AUDIO_CODEC_DAC,
	CLK_MCU_AUDIO_CODEC_ADC,
	CLK_BUS_MCU_AUDIO_CODEC,
	CLK_BUS_DSP_MSG,
	CLK_BUS_DSP_CFG,
	CLK_BUS_MCU_NPU_ACLK,
	CLK_BUS_MCU_NPU_HCLK,
	CLK_BUS_MCU_NPU,
	CLK_MCU_TIMER0,
	CLK_MCU_TIMER1,
	CLK_MCU_TIMER2,
	CLK_MCU_TIMER3,
	CLK_MCU_TIMER4,
	CLK_MCU_TIMER5,
	CLK_BUS_MCU_TIMER,
	CLK_BUS_MCU_DMA,
	CLK_BUS_MCU_TZMA0,
	CLK_BUS_MCU_TZMA1,
	CLK_BUS_PUBSRAM,
	CLK_BUS_MCU_MBUS,
	CLK_BUS_MCU_DMA_MBUS,
	CLK_BUS_RV,
	CLK_BUS_RV_CFG,
	CLK_BUS_MCU_RISCV_MSG,
	CLK_MCU_PWM,
	CLK_BUS_MCU_PWM,
	CLK_BUS_MCU_AHB_AUTO,

	CLK_MCU_NUMBER,
	};
#endif  /* _CCU_SUN55IW3_MCU_H_ */
